name: Build and push Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region us-east-1

    - name: Log in to aws ecr
      run: aws ecr get-login-password | docker login --username AWS --password-stdin 286928876767.dkr.ecr.us-east-1.amazonaws.com
  
    - name: Download dependencies
      run: |
        set -x
        ./mvnw -B quarkus:go-offline dependency:go-offline de.qaware.maven:go-offline-maven-plugin:1.2.8:resolve-dependencies
        docker pull registry.access.redhat.com/ubi8/openjdk-21:1.20
        docker compose pull
        docker pull 286928876767.dkr.ecr.us-east-1.amazonaws.com/datasqrl-cloud-compilation/cloud-compilation:1.0-SNAPSHOT

    - name: Create tmp work dir
      run: |
        mkdir -p /tmp/shared/
        chmod 777 /tmp/shared/

    - name: Build and push image with Maven
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: ./mvnw -B -Pci -Dtest=skip -Dquarkus.container-image.tag=${{ github.sha }}
